# Basic
title: Zachary
subtitle: 生于忧患，死于安乐
welcome_message: 这里不限于谈论技术，同时也会涉及个人兴趣爱好，如魂系列游戏、克苏鲁文学等。
description: Hi，我是 Zachary，一名 iOS 开发者，欢迎来到我的博客。
#creator: <a href="http://www.zacharymistraven">@Zachary</a>

url: "http://www.zacharymistraven.com/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: slate

# The blog button should not be removed.
blog_button:
    title: 博客
    description: 访问博客

# Navigation buttons in the front page.
#nav:
#    - {title: Projects, description: My Projects, url: 'http://www.zacharymistraven.com/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 20
paginate_path: "page/:num/"

# Comment
comment:
    disqus: Zachary
    # duoshuo: 
    
# Social
social:
    mail: poisontusk@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
